# Generated by Django 3.0.8 on 2020-08-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(choices=[(1, 'Android')], default=0),
        ),
    ]
